---
title: Analyze AOD vs. weight in dog breeds
author: Peter Carbonetto
output: workflowr::wflow_html
---

*Add introductory text here.*

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center")
```

*Add text here.*

```{r load-pkgs, message=FALSE, warning=FALSE}
library(ggplot2)
library(cowplot)
```

Import data
-----------

Read the height, weight and age-of-death (AOD) data for different
dog breeds. These data accompany [Jones *et al*, 2008][jones-2008].

```{r read-data}
dogs <- read.csv("../data/dogs.csv",stringsAsFactors = FALSE)
```

Find "best-fit" line
--------------------

Find the line that best predicts AOD given body weight (in pounds).

```{r fit-lm}
fit <- lm(AOD ~ weight,dogs)
b   <- coef(fit)
```

Plot AOD vs. body weight
------------------------

Plot age-of-death vs. body weight, along with the best-fit line (the
dashed, blue line). Compare with Figure 4 from Jones *et al* (2008).

```{r}
ggplot(dogs,aes(x = weight,y = AOD)) +
  geom_point(color = "black") +
  geom_abline(intercept = b["(Intercept)"],slope = b["weight"],
              color = "darkorange",linetype = "dashed") +
  theme_cowplot()
```

[jones-2008]: https://doi.org/10.1534/genetics.108.087866
